### ISSUE TITLE
AttributeError 'Options' object has no attribute 'get_ordered_objects' in Django 1.6

### ISSUE THREAD

**Issue by ghost** [jazzband/django-authority#37]
Hi, I'm using version 0.8 of django-authority and I'm following the documentation to create a per-object permission in Django 1.6. When in the admin I select an object from my class and try to 'Edit permissions for selected 'MyObject'", I get the following error:

AttributeError at /admin/activity/myobject/

'Options' object has no attribute 'get_ordered_objects'

Request Method:     POST
Request URL:    http://example.com/admin/activity/myobject/
Django Version:     1.6.2
Exception Type:     AttributeError
Exception Value:    

'Options' object has no attribute 'get_ordered_objects'

Exception Location:     .virtualenv/lib/python2.7/site-packages/authority/admin.py in edit_permissions, line 84
Python Executable:  /usr/bin/python
Python Version:     2.7.6

I found a ticket about the removal of 'get_ordered_objects' [1] and I can't find it in the source code for 1.6, but I don't know enough of what this function is used for, to comment it or replace it.

[1] https://code.djangoproject.com/ticket/19469

**Comment by jlward** [comment]
@bocribbz can you take a look at this while we are getting django 1.8 support?
