### ISSUE TITLE
django version

### ISSUE THREAD

**Issue by hpfn** [jazzband/django-authority#50]
Hi,

The Django-Authority Debian package is obsolete. Version 0.5.
The Django version in Debian testing/sid is 1.9.

The last version of Django-Authority (0.10) supports Django 1.9 ?
If so, I will try to upgrade the Debian package.

regards,
Herbert

**Comment by safwanrahman** [comment]
Hi @hpfn, We have not tested with django 1.9 yet. We are going to make a release soon, please be in touch.
Thanks for maintaining the debian package.
I will inform as soon as we make the release

**Comment by hpfn** [comment]
Em 15/06/2016 18:05, Safwan Rahman escreveu:
> Hi @hpfn <https://github.com/hpfn>, We have not tested with django 1.9
> yet. We are going to make a release soon, please be in touch.
> Thanks for maintaining the debian package.
> I will inform as soon as we make the release
>

Ok. Thanks for reply.



regards,
Herbert

**Comment by GregLeBarbar** [comment]
Hello,

I use your package since many years. Thanks for this package.
I have tested with django 1.9 and there are some change to do.
Can I help you ? Can I do a pull request for django 1.9 ? Or I'am coming too late ?

regards,
Greg

**Comment by safwanrahman** [comment]
> Can I help you ? Can I do a pull request for django 1.9 ? Or I'am coming too late ?

Sure, please make a pull request. We will be very happy to get it merged

**Comment by safwanrahman** [comment]
The package has been updated and made a new release
