### ISSUE TITLE
Latest version not on PyPI?

### ISSUE THREAD

**Issue by mitya57** [jazzband/django-authority#56]
Hi,

Django 1.10 support was added in version 0.12, but PyPI contains only 0.11: https://pypi.python.org/pypi/django-authority/.

**Comment by jlward** [comment]
+1

**Comment by safwanrahman** [comment]
Need to write a release note and make a release tag. It will be automatically pushed to Pypi

**Comment by safwanrahman** [comment]
https://github.com/jazzband/roadies/issues/83

**Comment by jezdez** [comment]
Now that https://github.com/jazzband/roadies/issues/83 has been fixed, the 0.12 and 0.13 releases are out. We also now have the ability to semi-automatically do releases again. So future release should happen quicker.
