### ISSUE TITLE
Most recent version on PyPi still uses `basestring`.

### ISSUE THREAD

**Issue by jlward** [jazzband/django-authority#63]
Although there is a fix in the code to stop using `basestring`, that has not been pushed to PyPi. Can we get a new version pushed to PyPi?

**Comment by benspaulding** [comment]
The [0.14 release tag](https://github.com/jazzband/django-authority/releases/tag/0.14) was recently made. I think now it just needs put up on PyPI.

**Comment by jezdez** [comment]
The build system was broken in the commit that added Django 2.2 support. I've since updated it and wokring on a 0.14 release. Closing as fixed.
